django_u2f/urls.py
from django.urls import re_path

from . import views

app_name = 'u2f'

urlpatterns = [
    re_path(r'^add-key/', views.add_key, name='add-u2f-key'),
    re_path(r'^verify-second-factor/', views.verify_second_factor, name='verify-second-factor'),
    re_path(r'^login/', views.login, name='login'),
    re_path(r'^keys/', views.keys, name='u2f-keys'),
    re_path(r'^two-factor-settings/', views.two_factor_settings, name='two-factor-settings'),
    re_path(r'^backup-codes/', views.backup_codes, name='backup-codes'),
    re_path(r'^add-totp-device/', views.add_totp, name='add-totp'),
    re_path(r'^totp-devices/', views.totp_devices, name='totp-devices'),
]

django_u2f/templates/u2f/add_key.html
{% extends "u2f/base.html" %}
{% load i18n %}
{% load static %}

{% block content %}
{{ block.super }}
<p>{% trans 'To add a security key to your account, insert (and tap) it.' %}</p>

<p id="u2f-status"></p>
<form method="post" id="u2f-form">
  {% csrf_token %}
  {{ form.response }}
</form>

{{ registration_request|json_script:"django_u2f_registration" }}
<script src="{% static 'django_u2f/django_u2f.js' %}"></script>
{% endblock %}

django_u2f/templates/u2f/backup_codes.html
{% extends "u2f/base.html" %}
{% load i18n %}

{% block content %}
{{ block.super }}

<a href="{% url 'u2f:two-factor-settings' %}">{% trans '&larr; Back to settings' %}</a>

<ul>
  {% for code in object_list %}
  <li>{{ code.code }}</li>
  {% empty %}
  <li>{% trans 'You do not have any backup codes! Please create some!' %}</li>
  {% endfor %}
</ul>

<form method="POST">
  {% csrf_token %}
  <input type="submit" value="{% trans 'Create some backup codes' %}">
</form>

{% endblock %}

django_u2f/templates/u2f/base.html
{% extends base_template|default:"base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
{{ block.super }}
<div id="webauthn-not-defined-error" style="display: none">
    {% blocktrans %}
    You must be using a compatible browser to use a security key with WebAuthn.
    {% endblocktrans %}
</div>
{% endblock %}

django_u2f/templates/u2f/key_list.html
{% extends "u2f/base.html" %}
{% load i18n %}

{% block content %}
{{ block.super }}
<h1>U2F Keys</h1>
<a href="{% url 'u2f:two-factor-settings' %}">{% trans '&larr; Back to settings' %}</a>
<table>
  <thead>
    <tr>
      <th>{% trans 'Added on' %}</th>
      <th>{% trans 'Last used on' %}</th>
    </tr>
  </thead>
  <tbody>
    {% for key in object_list %}
    <tr>
      <td>{{ key.created_at }}</td>
      {% trans 'Never' as never %}
      <td>{{ key.last_used_at|default:never }}</td>
      <td>
        <form method="post">{% csrf_token %}
          <input name="key_id" type="hidden" value="{{ key.pk }}">
          <input type="submit" name="delete" value="X">
        </form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<a href="{% url 'u2f:add-u2f-key' %}">{% trans 'Add another key' %}</a>
{% endblock %}

django_u2f/templates/u2f/login.html
{% extends "u2f/base.html" %}
{% load i18n %}

{% block content %}

<form method="post">
{% csrf_token %}
<table>
{{ form.as_p }}
</table>
<input type="submit" value="{% trans 'Login' %}" />
</form>

{% endblock %}

django_u2f/templates/u2f/totp_device.html
{% extends "u2f/base.html" %}
{% load i18n %}

{% block content %}
{{ block.super }}

<p>{% trans 'Scan this in your authenticator app:' %}</p>

<a href="{{ otpauth }}">
{{ qr_svg|safe }}
</a>

<p>
  {% trans "Or, if you can't scan a QR Code, enter this key as a time-based account:" %} <a href="{{ otpauth }}"><tt>{{ base32_key }}</tt></a>
</p>

<p>
  {% trans 'Then, enter the token it gives you.' %}
</p>

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="hidden" name="base32_key" value="{{ base32_key }}">
  <button value="backup" name="type">{% trans 'Submit' %}</button>
</form>

{% endblock %}

django_u2f/templates/u2f/totpdevice_list.html
{% extends "u2f/base.html" %}
{% load i18n %}

{% block content %}
{{ block.super }}
<h1>{% trans "TOTP (Authenticator) Devices" %}</h1>
<a href="{% url 'u2f:two-factor-settings' %}">{% trans '&larr; Back to settings' %}</a>
<table>
  <thead>
    <tr>
      <th>{% trans 'Added on' %}</th>
      <th>{% trans 'Last used on' %}</th>
    </tr>
  </thead>
  <tbody>
    {% for device in object_list %}
    <tr>
      <td>{{ device.created_at }}</td>
      {% trans 'Never' as never %}
      <td>{{ device.last_used_at|default:never}}</td>
      <td>
        <form method="post">{% csrf_token %}
          <input name="device_id" type="hidden" value="{{ device.pk }}">
          <input type="submit" name="delete" value="X">
        </form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<a href="{% url 'u2f:add-totp' %}">{% trans 'Add another TOTP (Authenticator) Device' %}</a>
{% endblock %}

django_u2f/templates/u2f/two_factor_settings.html
{% extends "u2f/base.html" %}
{% load i18n %}

{% block content %}
{{ block.super }}
<h1>{% trans "Two Factor Settings" %}</h1>
<ul>
  <li><a href="{% url 'u2f:u2f-keys' %}">{% trans 'Manage U2F keys' %}</a></li>
  <li><a href="{% url 'u2f:backup-codes' %}">{% trans 'Manage backup codes' %}</a></li>
  <li><a href="{% url 'u2f:totp-devices' %}">{% trans 'Manage TOTP (Authenticator) devices' %}</a></li>
</ul>

<h2>{% trans "Status" %}</h2>
<ul>
  <li>{% trans "U2F" %}: {% if u2f_enabled %}{% trans "On" %}{% else %}{% trans "Off" %}{% endif %}</li>
  <li>{% trans "TOTP" %}: {% if totp_enabled %}{% trans "On" %}{% else %}{% trans "Off" %}{% endif %}</li>
  <li>{% trans "Backup codes remaining" %}: {{ backup_codes | length }}</li>
</ul>

{% endblock %}

django_u2f/templates/u2f/verify_second_factor.html
{% extends "u2f/base.html" %}
{% load i18n %}
{% load static %}

{% block content %}
{{ block.super }}

<p>
  {% trans 'Please verify one of the authentication methods below.' %}
</p>

{% if forms.u2f %}
<div class="method u2f">
  <p>
  {% trans 'Insert your Security Key' %}
  </p>
  <p>
  {% blocktrans %}
  If your Security Key has a button, tap it.<br>
  If it doesn't, remove and re-insert it.
  {% endblocktrans %}
  </p>

  <p id="u2f-status"></p>
  <form method="post" id="u2f-form">
      {% csrf_token %}
      {{ forms.u2f.as_p }}
      <input type="hidden" name="type" value="u2f">
  </form>

  {{ forms.u2f.sign_request|json_script:"django_u2f_request" }}
</div>
{% endif %}

{% if forms.totp %}
<div class="method totp">
  <p>{% trans 'Enter an Authenticator (TOTP) Token:' %}</p>

  <form method="post">
    {% csrf_token %}
    {{ forms.totp.as_p }}
    <button value="totp" name="type">{% trans 'Submit' %}</button>
  </form>
</div>
{% endif %}

{% if forms.backup %}
<div class="method backup">
  <p>{% trans 'Use a backup code:' %}</p>

  <form method="POST">
    {% csrf_token %}
    {{ forms.backup.as_p }}
    <button value="backup" name="type">{% trans 'Submit' %}</button>
  </form>
</div>
{% endif %}

<script src="{% static 'django_u2f/django_u2f.js' %}"></script>
{% endblock %}